name: Go

on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Checkout
        uses: actions/checkout@v2
      - name: run
        run: |
          go run ./list >output
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            output

